[font]
size = 10

[font.normal]
family = "Hack"

[keyboard]
bindings = [
	{ key = "Return", mods = "Shift", chars = "\n" },
	{ key = "K", mods = "Control|Shift", chars = "\f" },
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
